if(NOT DEFINED IMGUI_BINDINGS_DIR)
    message(
        FATAL_ERROR
        "ImGui seems to be not set up directly."
        " ImGui must be generated by Conan and defined IMGUI_BINDINGS_DIR variable"
    )
endif()

find_package(imgui REQUIRED)
find_package(glfw3 REQUIRED)

function(add_imgui_bindings BACKEND_NAME DEPS)
    set(BACKEND_FILE "${IMGUI_BINDINGS_DIR}/imgui_impl_${BACKEND_NAME}.cpp")
    set(BACKEND_LIB imgui-bindings-${BACKEND_NAME})

    add_library(${BACKEND_LIB} STATIC ${BACKEND_FILE})
    target_include_directories(${BACKEND_LIB} PUBLIC ${IMGUI_BINDINGS_DIR})
    target_link_libraries(${BACKEND_LIB} PUBLIC imgui::imgui ${DEPS})

    add_library(imgui::bindings::${BACKEND_NAME} ALIAS ${BACKEND_LIB})
    message(STATUS "Add ImGui bindings: imgui::bindings::${BACKEND_NAME}")
endfunction()

add_imgui_bindings(glfw glfw)
add_imgui_bindings(opengl3 "")
